config/routes.rb
Rails.application.routes.draw do
  resources :customers
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def edit
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path, notice:'Cliente cadastrado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to customer_path(@customer.id), notice: 'Cliente atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    if @customer.destroy
      redirect_to customers_path, notice: 'Cliente excluido com sucesso.'
    else
      render :index
    end
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email, :phone, :avatar, :smoker)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/edit.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message|  %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>Editando Cliente</h1>

<%= form_for @customer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :email %>
  <%= f.text_field :email %> <br>

  <%= f.label :phone %>
  <%= f.text_field :phone %> <br>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %> <br>

  <%= f.label :smoker %> <br>
  <% {'S': 'Sim', 'N': 'Não'}.each do |k,v| %>
    <%= f.radio_button :smoker, k %> <%= v %> <br>
  <% end %>

  <%= f.submit 'Atualizar Cliente' %>
<% end %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>

<h1>Listando Clientes</h1>
<%= link_to 'Novo Cliente', new_customer_path %>


<table>
  <thead>
    <tr>
      <td>Nome</td>
      <td colspan="3"></td>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= link_to "Mostrar", customer_path(customer) %></td>
      <td><%= link_to "Editar", edit_customer_path(customer) %></td>
      <td><%= link_to "Excluir", customer_path(customer), method: :delete %></td>
      <!-- , data: { confirm: 'Realmente deseja excluir?' } -->
    </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message|  %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>Novo Cliente</h1>

<%= form_for @customer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :email %>
  <%= f.text_field :email %> <br>

  <%= f.label :phone %>
  <%= f.text_field :phone %> <br>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %> <br>

  <%= f.label :smoker %> <br>
  <% {'S': 'Sim', 'N': 'Não'}.each do |k,v| %>
    <%= f.radio_button :smoker, k %> <%= v %> <br>
  <% end %>

  <%= f.submit 'Criar Cliente' %>
<% end %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>

<h1>Mostrando Cliente</h1>
<p>
  <strong>Nome</strong>
  <%= @customer.name %>
</p>
<p>
  <strong>Email</strong>
  <%= @customer.email %>
</p>
<p>
  <strong>Telefone</strong>
  <%= @customer.phone %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddAppRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Bem-Vindo</h1>
<ul>
  <li><%= link_to "Cadastro de Clientes", customers_path %></li>
</ul>